// Uses Playwright supplied by the development environment (no runtime dependency).
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { mockSubmit } from './mock-submit.mjs';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [];
let expectedSubmissionFailure = false;
page.on('pageerror', (error) => errors.push(error.message));
page.on('response', (response) => { if (response.status() >= 400 && !expectedSubmissionFailure) errors.push(`${response.status()} ${response.url()}`); });
const field = (id) => page.locator(`#${id}`);
const click = (id) => field(id).click();
const next = () => click('next-button');
const visible = async (id) => {
  await field(id).waitFor({ state: 'visible', timeout: 5000 });
  assert.ok(await field(id).isVisible(), `${id} should be visible`);
};
const layout = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal overflow');
const photo = { name: 'conta-de-luz.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=', 'base64') };

try {
  await mkdir('outputs/refactor', { recursive: true });
  await mockSubmit(page);
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:4173');
  await page.screenshot({ path: 'outputs/refactor/desktop-inicio.png', fullPage: true });
  await page.locator('[data-service="solar"]').click();
  await next();
  assert.equal(await field('city-solar').getAttribute('aria-invalid'), 'true');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'city-solar');
  await field('city-solar').fill('Matinhos');
  await field('property-solar').selectOption('Residencial');
  await field('city-solar').press('Enter');
  await visible('consumption');
  await field('consumption').fill('-5');
  await next();
  await visible('consumption');
  assert.equal(await field('consumption').getAttribute('aria-invalid'), 'true');
  await field('consumption').fill('450.5');
  await next();
  await field('name').fill('Teste local');
  await field('phone').fill('12345678');
  await next();
  assert.equal(await field('phone').getAttribute('aria-invalid'), 'true');
  await field('phone').fill('+55 (41) 99999-9999');
  assert.match(await field('privacy-note').innerText(), /30 dias/);
  await field('notes').fill('<img src=x onerror=alert(1)> & ' + 'observação'.repeat(80));
  await next();
  await visible('result-view');
  assert.equal(await field('summary').locator('img').count(), 0, 'User text is not parsed as markup');
  const firstUrl = new URL(await field('send-whatsapp').getAttribute('href'));
  assert.equal(firstUrl.pathname, '/5541995587407', 'Solar request targets the confirmed WhatsApp number');
  assert.ok(firstUrl.searchParams.get('text').includes('*Consumo*\n• 450.5 kWh/mês'));
  assert.ok(!firstUrl.searchParams.get('text').includes('Não selecionada'));
  const internalId = /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i;
  assert.doesNotMatch(firstUrl.searchParams.get('text'), internalId);
  assert.doesNotMatch(await field('step-description').textContent(), internalId);
  assert.doesNotMatch(await field('summary').innerText(), /Não selecionada|A combinar/);
  assert.ok(firstUrl.searchParams.get('text').includes('(41) 99999-9999'));
  await layout();
  await click('edit-button');
  assert.match(await field('edit-note').innerText(), /pedido anterior já foi registrado/);
  assert.equal(await field('name').inputValue(), 'Teste local');
  await field('name').fill('Nome corrigido');
  await next();
  await page.waitForFunction(() => {
    const href = document.getElementById('send-whatsapp')?.getAttribute('href');
    return href && new URL(href).searchParams.get('text')?.includes('Nome corrigido');
  });
  assert.ok(new URL(await field('send-whatsapp').getAttribute('href')).searchParams.get('text').includes('Nome corrigido'));
  await click('edit-button');
  await click('back-button');
  await click('back-button');
  await click('back-button');
  await page.locator('[data-service="solar"]').click();
  assert.equal(await field('city-solar').inputValue(), 'Matinhos', 'Returning to same service preserves city');
  await next();
  assert.equal(await field('consumption').inputValue(), '450.5');

  await field('bill-photo').setInputFiles({ name: 'texto.txt', mimeType: 'text/plain', buffer: Buffer.from('test') });
  assert.match(await field('error-message').textContent(), /imagem JPG, PNG ou WebP/);
  assert.equal(await field('bill-photo').evaluate((input) => input.files.length), 0);
  await field('bill-photo').setInputFiles({ ...photo, buffer: Buffer.alloc(4 * 1024 * 1024 + 1) });
  assert.match(await field('error-message').textContent(), /4 MB/);
  await field('bill-photo').setInputFiles(photo);
  assert.equal(await field('clear-bill-photo').isVisible(), true);
  await click('clear-bill-photo');
  assert.equal(await field('bill-photo').evaluate((input) => input.files.length), 0);
  assert.equal(await field('clear-bill-photo').isVisible(), false);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'bill-photo');
  await field('bill-photo').setInputFiles(photo);
  await field('consumption').fill('');
  await page.setViewportSize({ width: 390, height: 844 });
  await field('bill-photo').focus();
  assert.equal(await field('bill-photo').evaluate((input) => getComputedStyle(input.closest('.file-drop')).outlineStyle), 'solid');
  await layout();
  await page.screenshot({ path: 'outputs/refactor/mobile-consumo.png', fullPage: true });
  await next();
  await next();
  await visible('result-view');
  assert.match(await field('summary').textContent(), /conta de luz recebida pelo formulário/i);
  assert.doesNotMatch(await field('summary').textContent(), /Conta de luz\s+Recebida pelo formulário/);
  assert.doesNotMatch(await field('summary').textContent(), /Foto da conta anexada/);
  await layout();
  await page.screenshot({ path: 'outputs/refactor/mobile-resumo.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 700 });
  await layout();
  await page.evaluate(() => { document.documentElement.style.fontSize = '32px'; });
  await page.waitForFunction(() => getComputedStyle(document.documentElement).fontSize === '32px');
  await layout();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal overflow at 320px with 200% text');
  await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
  await page.waitForFunction(() => getComputedStyle(document.documentElement).fontSize === '16px');

  await click('edit-button');
  for (let i = 0; i < 3; i++) await click('back-button');
  await page.locator('[data-service="pattern"]').click();
  await field('city-pattern').fill('Pontal do Paraná');
  await field('property-pattern').selectOption('Comercial');
  await next();
  assert.match(await field('error-message').textContent(), /resolver/);
  await page.locator('[data-case="Troca ou adequação"]').click();
  await next();
  await next();
  assert.match(await field('error-message').textContent(), /projeto/);
  await page.locator('[data-project="Ainda não"]').click();
  await field('voltage').selectOption('Não sei');
  await next();
  await field('phone').fill('(41) 3333-4444');
  await field('notes').fill('');
  await next();
  await visible('result-view');
  assert.match(await field('summary').textContent(), /Troca ou adequação/);
  assert.doesNotMatch(await field('summary').textContent(), /Não selecionada|A combinar/);
  assert.doesNotMatch(await field('summary').textContent(), /conta-de-luz|Consumo médio/);
  const patternMessage = new URL(await field('send-whatsapp').getAttribute('href')).searchParams.get('text');
  assert.equal(new URL(await field('send-whatsapp').getAttribute('href')).pathname, '/5541995587407', 'Pattern request targets the confirmed WhatsApp number');
  assert.match(patternMessage, /\n\*Detalhes\*\n• Necessidade: Troca ou adequação/);
  assert.match(patternMessage, /\n\*Contato\*\n• Nome:/);
  assert.doesNotMatch(patternMessage, /Não selecionada|Conta de luz/);
  await layout();
  await page.screenshot({ path: 'outputs/refactor/mobile-poste.png', fullPage: true });

  await click('edit-button');
  await field('notes').fill('Ajuste fictício');
  const contactBeforeFailure = await field('name').inputValue();
  await page.unroute('**/api/submit');
  await page.route('**/api/submit', route => route.fulfill({
    status: 500,
    contentType: 'text/plain',
    body: 'Error: Cannot find module netlify/lib/order.mjs'
  }));
  expectedSubmissionFailure = true;
  const failedSubmission = page.waitForResponse((response) => response.url().includes('/api/submit') && response.status() === 500);
  await Promise.all([failedSubmission, next()]);
  await page.waitForFunction(() => document.querySelector('#error-message')?.textContent?.includes('Não foi possível confirmar o registro'));
  expectedSubmissionFailure = false;
  assert.match(await field('error-message').innerText(), /Não foi possível confirmar o registro/);
  assert.doesNotMatch(await field('error-message').innerText(), /Error|module|Netlify|Tesseract/i);
  assert.equal(await field('name').inputValue(), contactBeforeFailure, 'Failed submissions preserve the contact data');
  assert.equal(await field('phone').inputValue(), '(41) 3333-4444', 'Failed submissions preserve the phone');
  await page.unroute('**/api/submit');
  await mockSubmit(page);
  await next();
  await visible('result-view');
  await click('restart-button');
  await page.locator('[data-service="solar"]').click();
  assert.equal(await field('city-solar').inputValue(), '');
  assert.equal(await field('name').inputValue(), '');
  assert.equal(await field('bill-photo').evaluate((input) => input.files.length), 0);
  assert.equal(await field('summary').textContent(), '');
  assert.equal(await field('send-whatsapp').getAttribute('href'), null);
  const noJsContext = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
  try {
    const noJsPage = await noJsContext.newPage();
    await noJsPage.goto(process.env.BASE_URL || 'http://127.0.0.1:4173');
    const warning = noJsPage.locator('noscript p');
    assert.equal(await warning.innerText(), 'Ative o JavaScript no navegador para preencher o formulário.');
    assert.ok(await warning.evaluate((element) => element.getBoundingClientRect().top < innerHeight), 'No-JS instruction must be visible without scrolling');
    assert.equal(await noJsPage.locator('.form-card').isVisible(), false, 'Nonfunctional form must be hidden without JavaScript');
    await noJsPage.waitForTimeout(100);
    await noJsPage.screenshot({ path: 'outputs/refactor/noscript.png' });
  } finally {
    await noJsContext.close();
  }
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: both services, Enter, validation, photos, edit, preservation, reset, safe rendering, responsive layout, 200% text and no console/HTTP errors. No WhatsApp message sent.');
} finally {
  await browser.close();
}
