import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { mockSubmit } from './mock-submit.mjs';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
const gallery = page.locator('#service-gallery');
const main = page.locator('#gallery-main');
const thumbs = page.locator('.gallery-thumb');
const selected = async () => new URL(await main.getAttribute('src'), page.url()).pathname;
const assertLoaded = async () => assert.ok(await main.evaluate(image => image.complete && image.naturalWidth > 0));
const assertContained = async () => assert.equal(await main.evaluate(image => getComputedStyle(image).objectFit), 'contain');
const assertLayout = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));

try {
  await mkdir('outputs/gallery-qa', { recursive: true });
  await mockSubmit(page);
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
  assert.equal(await gallery.isVisible(), false, 'No gallery on service choice');
  await page.locator('[data-service="solar"]').click();
  assert.ok(await gallery.isVisible());
  assert.equal(await selected(), '/assets/solar-01.jpg');
  assert.equal(await thumbs.count(), 2);
  assert.match(await main.getAttribute('alt'), /Painéis solares/);
  await assertLoaded();
  await assertContained();
  const initialHeight = await gallery.evaluate(element => element.getBoundingClientRect().height);
  assert.ok(initialHeight <= 260, `Mobile gallery is too tall: ${initialHeight}`);
  assert.equal(await page.locator('#city-solar').isVisible(), true);
  await page.screenshot({ path: 'outputs/gallery-qa/solar-mobile.png', fullPage: true });
  await thumbs.first().click();
  assert.equal(await selected(), '/assets/solar-02.jpg');
  assert.equal(await page.locator('#gallery-counter').innerText(), 'Foto 2 de 3');
  await assertLoaded();
  await assertContained();
  await thumbs.last().focus();
  await page.keyboard.press('Enter');
  assert.equal(await selected(), '/assets/solar-03.jpg');
  await assertLoaded();
  await assertContained();
  assert.equal(await thumbs.first().getAttribute('type'), 'button');
  await page.locator('#city-solar').fill('Matinhos');
  await page.locator('#property-solar').selectOption('Residencial');
  await page.locator('#next-button').click();
  assert.equal(await gallery.isVisible(), false, 'Gallery hidden on consumption step');
  await page.locator('#consumption').fill('450');
  await page.locator('#next-button').click();
  assert.equal(await gallery.isVisible(), false, 'Gallery hidden on contact step');
  await page.locator('#back-button').click();
  await page.locator('#back-button').click();
  assert.equal(await selected(), '/assets/solar-03.jpg', 'Photo kept when returning');
  await page.locator('#back-button').click();
  assert.equal(await gallery.isVisible(), false, 'No gallery on choice step after returning');
  await page.locator('[data-service="pattern"]').click();
  assert.equal(await selected(), '/assets/pattern-01.jpg');
  assert.equal(await thumbs.count(), 2);
  await assertLoaded();
  await assertContained();
  await page.screenshot({ path: 'outputs/gallery-qa/pattern-mobile.png', fullPage: true });
  await thumbs.first().focus();
  await page.keyboard.press('Enter');
  assert.equal(await selected(), '/assets/pattern-02.jpg');
  await assertLoaded();
  await thumbs.last().click();
  assert.equal(await selected(), '/assets/pattern-03.jpg');
  await assertLoaded();
  await page.locator('#back-button').click();
  await page.locator('[data-service="solar"]').click();
  assert.equal(await selected(), '/assets/solar-03.jpg', 'Separate selection per service');
  await page.setViewportSize({ width: 1440, height: 900 });
  await assertLayout();
  await page.screenshot({ path: 'outputs/gallery-qa/solar-desktop.png', fullPage: true });
  await page.locator('#back-button').click();
  await page.locator('[data-service="pattern"]').click();
  assert.equal(await selected(), '/assets/pattern-03.jpg');
  await page.screenshot({ path: 'outputs/gallery-qa/pattern-desktop.png', fullPage: true });
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 844 });
    await assertLayout();
  }
  await page.setViewportSize({ width: 320, height: 700 });
  await page.evaluate(() => { document.documentElement.style.fontSize = '32px'; });
  await page.waitForFunction(() => getComputedStyle(document.documentElement).fontSize === '32px');
  await assertLayout();
  assert.ok(await thumbs.first().evaluate(button => button.getBoundingClientRect().right <= innerWidth));
  await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
  await page.locator('#city-pattern').fill('Pontal do Paraná');
  await page.locator('#property-pattern').selectOption('Residencial');
  await page.locator('[data-case="Instalação nova"]').click();
  await page.locator('#next-button').click();
  await page.locator('[data-project="Ainda não"]').click();
  await page.locator('#next-button').click();
  await page.locator('#name').fill('Pessoa Teste');
  await page.locator('#phone').fill('(41) 99999-9999');
  await page.locator('#next-button').click();
  assert.equal(await gallery.isVisible(), false, 'Gallery hidden in summary');
  await page.locator('#restart-button').click();
  assert.equal(await gallery.isVisible(), false);
  await page.locator('[data-service="pattern"]').click();
  assert.equal(await selected(), '/assets/pattern-01.jpg', 'Reset returns to primary image');
  await page.locator('#back-button').click();
  await page.locator('[data-service="solar"]').click();
  assert.equal(await selected(), '/assets/solar-01.jpg', 'Reset returns both services to primary image');
  assert.deepEqual(errors, []);
  console.log('Gallery checks passed: selected assets, keyboard/mouse, per-service state, step visibility, reset, image loading, mobile/desktop layout.');
} finally {
  await browser.close();
}
